name = "Aawaz Order"
client_id = "ef0a177de62447a4f716403a40418b6c"
application_url = "https://aawaz-order.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

[access_scopes]
scopes = "read_products,write_orders,read_orders,write_draft_orders,read_draft_orders,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://aawaz-order.vercel.app/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/redact"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  compliance_topics = ["shop/redact"]
  uri = "/webhooks"

[pos]
embedded = false
