name = "Aawaz Order"
client_id = "{{ SHOPIFY_API_KEY }}"
application_url = "{{ SHOPIFY_APP_URL }}"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

[access_scopes]
scopes = "read_products,write_orders,read_orders,write_draft_orders,read_draft_orders,read_customers,write_customers"

[auth]
redirect_urls = [
  "{{ SHOPIFY_APP_URL }}/auth/callback"
]

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  topics = ["customers/redact"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["shop/redact"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["customers/data_request"]
  uri = "/webhooks"

[pos]
embedded = false
